### ISSUE TITLE
도메인 파일들과 mybatis 연동 기능

### ISSUE THREAD

**Issue by ak2j38** [f-lab-edu/in-bob-we-trust#26]
- 작업 목록
  - [ ] 도메인 목록에 대한 mapper.java 파일 작성
  - [ ] repository interface 파일 작성
  - [ ] DB 연결 관련 테스트 파일 작성

**Comment by JooHyukKim** [comment]
## Notes
- Issue #82 로 필요성이 사라진 이슈입니다.
